### ISSUE TITLE
overflow when using bit_depth==32 in wavpack writing

### ISSUE THREAD

**Issue by mazbox** [colugomusic/blahdio#2]
Using the following code, I get an overflow (e.g. sample value wrapping around from +1 to -1 at the peak of the sine wave) - only at 32 bit:
`
	blahdio::AudioDataFormat write_format;

	uint32_t num_frames = 44100 * 10;
	write_format.bit_depth = 32;
	write_format.num_channels = 2;
	write_format.num_frames = num_frames;
	write_format.sample_rate = 44100;
	
	
	blahdio::AudioWriter writer("/Users/marek/Desktop/file.wv", blahdio::AudioType::WavPack, write_format);

	blahdio::AudioWriter::Callbacks writer_callbacks;

	writer_callbacks.should_abort = []() { return false; };

	double phase = 0.0;
	writer_callbacks.get_next_chunk = [&](float* buffer, std::uint64_t frame, std::uint32_t num_frames) {
		for(int i = 0; i < num_frames; i++) {
			float o = sin(phase);
			phase += 3.14159*2 * 256 / 44100.0;
			buffer[i*2] = o;
			buffer[i*2+1] = o;
		}
	};

	writer.write_frames(writer_callbacks, 512); // Will throw an exception if an error
`

screenshot:
<img width="1109" alt="Screenshot 2021-05-17 at 16 14 07" src="https://user-images.githubusercontent.com/194121/118512703-f2814680-b72a-11eb-9210-6ad2ef29dcc9.png">
Not important to me, as 32 bit audio files are overkill in my case, but I'm guessing it's a float math rounding problem maybe in wavpack_writer.cpp

**Comment by colugomusic** [comment]
Seems to be fixed by c1697b03ea1ab7dd9ffcd9b7a56b255328d2dcad

The test I added now passes on the LInux VM where previously it was failing:
https://github.com/colugomusic/blahdio/runs/2603855547
