### ISSUE TITLE
undefined AudioReader(AudioReader::Stream&, AudioType)

### ISSUE THREAD

**Issue by mazbox** [colugomusic/blahdio#3]
when using AudioReader with a Stream

added this to audio_reader.cpp to fix it.

`
AudioReader::AudioReader(const blahdio::AudioReader::Stream& stream, AudioType type_hint)
: impl_(std::make_shared<impl::AudioReader>(stream, type_hint))
{
}
`

**Comment by colugomusic** [comment]
Fixed by https://github.com/colugomusic/blahdio/pull/4 thanks marek!
